### PR TITLE
support webpack

### PR DESCRIPTION
**Pull request by sophyallen**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe):

## What is the current behavior?

- In the new Test VSCode instance which is lanched to test and debug, breakpoint is not available

## What is the new behavior?

- Support breakpoint debugging in new Extension VScode instances via 'Extions Run' launch script
- Support unit tests  via 'Unit Tests' launch script

### CODE REVIEW

**Review by sophyallen — COMMENTED** [review]
all right

**Comment by sophyallen** [comment]
@yubing744 I have checked the code and work well on my pc, Can you review, pls

**Comment by yubing744** [comment]
later

**Review by yubing744 — APPROVED** [review]
I have it running locally and it's really great

**Pull request merged**
